name: ticoi
channels:
  - conda-forge
dependencies:
  - aiohttp
  - dask
  - fiona
  - geopandas
  - h5netcdf
  - h5py
  - jdcal
  - matplotlib
  - notebook
  - numba
  - numpy
  - pandas
  - pyproj
  - rasterio
  - requests
  - rioxarray
  - scikit-learn
  - scipy
  - seaborn
  - shapely
  - statsmodels
  - tqdm
  - xarray
  - zarr
