name: ticoi
channels:
  - conda-forge
dependencies:
  - python=3.11
  - aiohttp
  - dask
  - fiona=1.9
  - gdal
  - geopandas>=0.10.0
  - h5netcdf
  - h5py>=3.11
  - jdcal
  - matplotlib=3.*
  - netcdf4
  - notebook
  - numba=0.*
  - numpy=1.*
  - pandas
  - pip
  - pyproj>=3.4
  - rasterio>=1.3
  - requests
  - rioxarray
  - scikit-learn
  - scipy=1.*
  - seaborn
  - shapely
  - statsmodels
  - tqdm
  - xarray
  - zarr
