name: ticoi
channels:
  - conda-forge
dependencies:
  - dask
  - geopandas
  - jdcal
  - h5netcdf
  - matplotlib
  - notebook
  - netcdf4
  - numba
  - numpy
  - pandas
  - pyproj
  - rasterio
  - requests
  - rioxarray
  - scipy
  - seaborn
  - shapely
  - statsmodels
  - tqdm
  - xarray
  - zarr
