name: Python test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAMBA_ROOT_PREFIX: /home/runner/mamba

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10 and Miniconda (no env creation yet)
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-version: latest
        auto-update-conda: true
        use-mamba: true
        mamba-version: "2.0.5"
        channel-priority: strict
        activate-environment: false
        python-version: "3.10"

    - name: Get month for resetting cache
      id: get-date
      run: echo "cache_date=$(/bin/date -u '+%Y%m')" >> $GITHUB_ENV
      shell: bash

    - name: Cache conda env
      uses: actions/cache@v4
      with:
        path: /home/runner/mamba/envs
        key: conda-ubuntu-latest-3.10-${{ env.cache_date }}-${{ hashFiles('environment.yml') }}-${{ env.CACHE_NUMBER }}
      env:
        CACHE_NUMBER: 0
      id: cache

    - name: Create or update environment if cache miss
      # if: steps.cache.outputs.cache-hit != 'true'
      run: |
        unset PROJ_DATA
        mamba env create -n environment -f environment.yml

    - name: Install project (inside env)
      run: mamba run -n environment pip install -e . --no-dependencies

    - name: Install test dependencies (inside env)
      run: mamba run -n environment pip install pytest

    - name: Check import works
      run: mamba run -n environment python -c "import ticoi"

    - name: Test with pytest
      run: mamba run -n environment pytest
