# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Initiate empty environment
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-version: latest
        auto-update-conda: true
        use-mamba: true
        mamba-version: "2.0.5"
        channel-priority: strict
        activate-environment: ticoi_env
        python-version: "3.10"

  #GitHub Actions treats the cache key as different → it skips reusing an old conda env and builds a fresh one.
    - name: Get month for resetting cache
      id: get-date
      run: echo "cache_date=$(/bin/date -u '+%Y%m')" >> $GITHUB_ENV
      shell: bash

  #Installing all conda dependencies (especially heavy ones like gdal, graphviz, numpy, etc.) is slow. This step avoids redoing that work every time.
    - name: Cache conda env
      uses: actions/cache@v4
      with:
        path: ${{ env.CONDA }}/envs
        key: conda-ubuntu-latest-3.10-${{ env.cache_date }}-${{ hashFiles('dev-environment.yml') }}-${{ env.CACHE_NUMBER }}
      env:
        CACHE_NUMBER: 0
      id: cache

    - name: Install project
      run: |
        mamba activate ticoi_env
        pip install -e . --no-dependencies #to install ticoi package

    - name: Check import works with base environment
      run: |
        unset PROJ_DATA
        python -c "import ticoi"

    - name: Setup pip dependencies
      run: |
        mamba activate ticoi_env
        pip install pytest

    - name: Update environment with development packages if cache does not exist
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        unset PROJ_DATA
        mamba env update -n ticoi_env -f ticoi_env.yml

    # - name: Lint with flake8
    #   run: |
    #     # stop the build if there are Python syntax errors or undefined names
    #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: List installed packages
      run: mamba list

    - name: Test with pytest
      run: mamba run -n ticoi_env pytest
